# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('cottage_booking_status', models.CharField(choices=[('FR', 'free'), ('BK', 'booked'), ('AM', 'bookedAm'), ('PM', 'bookedPm')], default='FR', max_length=1)),
                ('barn_booking_status', models.CharField(choices=[('FR', 'free'), ('BK', 'booked'), ('AM', 'bookedAm'), ('PM', 'bookedPm')], default='FR', max_length=1)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='dates',
            field=models.ManyToManyField(to='bookings.AvailabilityDate'),
        ),
    ]
