# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20180114_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=0, help_text='Enter the full-week price', max_digits=4)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='availabilitydate',
            name='barn_week_price',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='availabilitydate',
            name='cottage_week_price',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pricingperiod',
            name='dates',
            field=models.ManyToManyField(to='bookings.AvailabilityDate'),
        ),
        migrations.AddField(
            model_name='pricingperiod',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Property'),
        ),
    ]
