# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-04 10:05
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20180304_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingperiod',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Enter the full-week price', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
