# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-04 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20180304_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitydate',
            name='barn_week_price_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availabilitydate',
            name='cottage_week_price_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingperiod',
            name='discount',
            field=models.BooleanField(default=False, help_text='Select to mark price as discounted'),
        ),
    ]
